### ISSUE TITLE
Directory / process related errors 

### ISSUE THREAD

**Issue by katkasian** [SamHames/hyperreal#26]
Getting the below error when running `hyperreal stackexchange-corpus index travel_sx.db travel_sx_index.db`:

```
(venv) PS C:\Users\NXXXXX\qutscripts\PycharmProjects\hyperreal> hyperreal stackexchange-corpus index travel_sx.db travel_sx_index.db
Indexing travel_sx.db into travel_sx_index.db.
defaultdict(<class 'list'>, {0: ['C:\\Users\\NXXXXX~1\\AppData\\Local\\Temp\\tmpvgyzcycl\\0']})
defaultdict(<class 'list'>, {0: ['C:\\Users\\NXXXXX~1\\AppData\\Local\\Temp\\tmpvgyzcycl\\0', 'C:\\Users\\NXXXXX~1\\AppData\\Local\\Temp\\tmpvgyzcycl\\
1']})
defaultdict(<class 'list'>, {0: ['C:\\Users\\NXXXXX~1\\AppData\\Local\\Temp\\tmpvgyzcycl\\0', 'C:\\Users\\NXXXXX~1\\AppData\\Local\\Temp\\tmpvgyzcycl\\
1', 'C:\\Users\\NXXXXX~1\\AppData\\Local\\Temp\\tmpvgyzcycl\\7']})
defaultdict(<class 'list'>, {0: ['C:\\Users\\NXXXXX~1\\AppData\\Local\\Temp\\tmpvgyzcycl\\0', 'C:\\Users\\NXXXXX~1\\AppData\\Local\\Temp\\tmpvgyzcycl\\
1', 'C:\\Users\\NXXXXX~1\\AppData\\Local\\Temp\\tmpvgyzcycl\\7', 'C:\\Users\\NXXXXX~1\\AppData\\Local\\Temp\\tmpvgyzcycl\\2']})
Traceback (most recent call last):
  File "c:\users\nXXXXXX\qutscripts\pycharmprojects\hyperreal\hyperreal\index.py", line 537, in index
    os.remove(next_temp_file)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\NXXXXX~1\\AppData\\Local\\Te
mp\\tmpvgyzcycl\\13'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NXXXXXX\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 617, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\NXXXXX~1\\AppData\\Local\\Te
mp\\tmpvgyzcycl\\13'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NXXXXXX\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 820, in onerror
    _os.unlink(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\NXXXXX~1\\AppData\\Local\\Te
mp\\tmpvgyzcycl\\13'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NXXXXXX\qutscripts\PycharmProjects\hyperreal\venv\Scripts\hyperreal-script.py", line 33, in <module>
    sys.exit(load_entry_point('hyperreal', 'console_scripts', 'hyperreal')())
  File "C:\Users\NXXXXXX\qutscripts\PycharmProjects\hyperreal\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\NXXXXXX\qutscripts\PycharmProjects\hyperreal\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\NXXXXXX\qutscripts\PycharmProjects\hyperreal\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\NXXXXXX\qutscripts\PycharmProjects\hyperreal\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\NXXXXXX\qutscripts\PycharmProjects\hyperreal\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\NXXXXXX\qutscripts\PycharmProjects\hyperreal\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\nXXXXXX\qutscripts\pycharmprojects\hyperreal\hyperreal\cli.py", line 159, in stackexchange_corpus_index
    doc_index.index(doc_batch_size=doc_batch_size)
  File "c:\users\nXXXXXX\qutscripts\pycharmprojects\hyperreal\hyperreal\index.py", line 145, in wrapper_func
    return func(self, *args, **kwargs)
  File "c:\users\nXXXXXX\qutscripts\pycharmprojects\hyperreal\hyperreal\index.py", line 380, in index
    with tempfile.TemporaryDirectory() as tempdir:
  File "C:\Users\NXXXXXX\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 846, in __exit__
    self.cleanup()
  File "C:\Users\NXXXXXX\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 850, in cleanup
    self._rmtree(self.name, ignore_errors=self._ignore_cleanup_errors)
  File "C:\Users\NXXXXXX\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 832, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Users\NXXXXXX\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 749, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\NXXXXXX\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 619, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\NXXXXXX\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 823, in onerror
    cls._rmtree(path, ignore_errors=ignore_errors)
  File "C:\Users\NXXXXXX\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 832, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Users\NXXXXXX\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 749, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\NXXXXXX\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 600, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "C:\Users\NXXXXXX\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 597, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\NXXXXX~1\\AppData\\Local\\Temp\\tmpvgyzcycl\\13'
(venv) PS C:\Users\NXXXXXX\qutscripts\PycharmProjects\hyperreal> 
```

**Comment by SamHames** [comment]
I'm looking at this one now - I'll also see if I can add windows to the CI build so I catch this earlier, sorry about this one.

**Comment by SamHames** [comment]
Give it a try on main again - I think I fixed it. I also added windows and mac to test automatically in the CI config, so hopefully I will catch problems earlier.

**Comment by katkasian** [comment]
Thank you Sam, can confirm that it's fixed!
