### ISSUE TITLE
500 error when pivoting by cluster

### ISSUE THREAD

**Issue by katkasian** [SamHames/hyperreal#32]
Getting this error after pulling new updates from the main branch:

```
Traceback (most recent call last):
  File "C:\Users\NXXXXX\qutscripts\PycharmProjects\hyperreal\venv\lib\site-packages\cherrypy\_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "C:\Users\NXXXXX\qutscripts\PycharmProjects\hyperreal\venv\lib\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "C:\Users\NXXXXX\qutscripts\PycharmProjects\hyperreal\venv\lib\site-packages\cherrypy\lib\encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Users\NXXXXX\qutscripts\PycharmProjects\hyperreal\venv\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "c:\users\NXXXXX\qutscripts\pycharmprojects\hyperreal\hyperreal\server.py", line 167, in index
    rendered_docs = cherrypy.request.index.render_docs(ranked)
  File "c:\users\NXXXXX\qutscripts\pycharmprojects\hyperreal\hyperreal\index.py", line 56, in wrapper_func
    return func(self, *args, **kwargs)
  File "c:\users\NXXXXX\qutscripts\pycharmprojects\hyperreal\hyperreal\index.py", line 551, in render_docs
    return self.corpus.render_docs_html(doc_keys)
  File "c:\users\NXXXXX\qutscripts\pycharmprojects\hyperreal\hyperreal\corpus.py", line 619, in render_docs_html
    docs = [(key, self._render_doc_key(key)) for key in doc_keys]
  File "c:\users\NXXXXX\qutscripts\pycharmprojects\hyperreal\hyperreal\corpus.py", line 619, in <listcomp>
    docs = [(key, self._render_doc_key(key)) for key in doc_keys]
  File "c:\users\NXXXXX\qutscripts\pycharmprojects\hyperreal\hyperreal\corpus.py", line 545, in _render_doc_key
    base_fields = list(
IndexError: list index out of range
```

**Comment by katkasian** [comment]
Pivots by clusters or features within clusters appear to be affected.

**Comment by SamHames** [comment]
The error looks like a problem with retrieving documents from the corpus. Would you be able to drop the corpus db file into our shared google drive so I can take a look? It might be that I changed the corpus schema without realising it.

**Comment by katkasian** [comment]
Sorry for missing this Sam - here is the folder with the db files I am seeing the issue with - https://drive.google.com/drive/u/1/folders/1TeJUWyoe7x_RH4cNfJvzqfPzfjG6V4RM.
