### ISSUE TITLE
Nice-to-have: Error handling of cluster selection when mistakenly not specifying clusters

### ISSUE THREAD

**Issue by katkasian** [SamHames/hyperreal#64]
I stumbled upon a very minor scenario where not specifying a number of clusters when editing them throws a 500 error, so documenting it here.

### Steps to reproduce

1. Select a cluster for editing from the page with all clusters using a checkbox
2. Click "Edit selected clusters" option
3. Click "Refine selected clusters" without providing a number of clusters
4. See a 500 Error / KeyError appear:

```
Traceback (most recent call last):
  File "C:\Users\<user>\hyperreal\venv\lib\site-packages\cherrypy\_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "C:\Users\<user>l\venv\lib\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "C:\Users\<user>\hyperreal\venv\lib\site-packages\cherrypy\lib\encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Users\<user>\hyperreal\venv\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "c:\users\<user>hyperreal\hyperreal\server.py", line 198, in refine
    cherrypy.request.index.refine_clusters(
  File "c:\users\<user>\hyperreal\hyperreal\index.py", line 101, in wrapper
    results = func(*args, **kwargs)
  File "c:\users\<user>\hyperreal\hyperreal\index.py", line 1793, in refine_clusters
    cluster_feature, new_cluster_ids = self._refine_feature_groups(
  File "c:\users\<user>\hyperreal\hyperreal\index.py", line 1692, in _refine_feature_groups
    comparison_delta, comparison_cluster = best_feature_clusters[
KeyError: 8194
```

**Comment by SamHames** [comment]
Good catch, thanks!
