### ISSUE TITLE
Pathing / directory issue (may be Windows-specific) when attempting to write to a Temp directory

### ISSUE THREAD

**Issue by katkasian** [SamHames/hyperreal#7]
Getting the below error when trying to create an index from a corpus `hyperreal plaintext-corpus index corpus.db corpus_index.db`:

```
Indexing corpus.db into corpus_index.db.
Traceback (most recent call last):
  File "C:\Users\<...>\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 625, in _
rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by an
other process: 'C:\\Users\\<...>\\AppData\\Local\\Temp\\tmpp5wq8h2m\\0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\<...>\AppData\Local\Programs\Python\Python39\lib\tempfile.py", line 805, in
 onerror
    _os.unlink(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by an
other process: 'C:\\Users\\<...>\\AppData\\Local\\Temp\\tmpp5wq8h2m\\0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\<...>\PycharmProjects\hyperreal\venv\Scripts\hyperreal-script.py", line 33,
 in <module>
    sys.exit(load_entry_point('hyperreal', 'console_scripts', 'hyperreal')())
  File "C:\Users\<...>\PycharmProjects\hyperreal\venv\lib\site-packages\click\core.py", line
 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\<...>\PycharmProjects\hyperreal\venv\lib\site-packages\click\core.py", line
 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\<...>\PycharmProjects\hyperreal\venv\lib\site-packages\click\core.py", line
 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\<...>\PycharmProjects\hyperreal\venv\lib\site-packages\click\core.py", line
 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\N10980695\PycharmProjects\hyperreal\venv\lib\site-packages\click\core.py", line
 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\<...>\PycharmProjects\hyperreal\venv\lib\site-packages\click\core.py", line
 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\<...>\pycharmprojects\hyperreal\hyperreal\cli.py", line 69, in plaintext_co
rpus_index
    doc_index.index()
  File "c:\users\<...>\pycharmprojects\hyperreal\hyperreal\index.py", line 364, in index    
    self.save_corpus()
  File "C:\Users\<...>\AppData\Local\Programs\Python\Python39\lib\tempfile.py", line 830, in
 __exit__
    self.cleanup()
  File "C:\Users\<...>\AppData\Local\Programs\Python\Python39\lib\tempfile.py", line 834, in
 cleanup
    self._rmtree([self.name](http://self.name/))
  File "C:\Users\<...>\AppData\Local\Programs\Python\Python39\lib\tempfile.py", line 816, in
 _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Users\<...>\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 749, in r
mtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\<...>\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 627, in _
rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\<...>\AppData\Local\Programs\Python\Python39\lib\tempfile.py", line 808, in
 onerror
    cls._rmtree(path)
  File "C:\Users\<...>\AppData\Local\Programs\Python\Python39\lib\tempfile.py", line 816, in
 _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Users\<...>\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 749, in r
mtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\<...>\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 608, in _
rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "C:\Users\<...>\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 605, in _
rmtree_unsafe
    with os.scandir(path) as scandir_it:
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\<...>\\AppData\
\Local\\Temp\\tmpp5wq8h2m\\0'
```

The issue appears to be similar to https://github.com/Belval/pdf2image/issues/151.

**Environment** : Windows 10, winver 21H2

**Comment by SamHames** [comment]
I think that is windows specific, but I thought the standard library functions would handle that - I will do some digging today, but might not make much progress until I'm back in front of the windows machine in the office.

**Comment by SamHames** [comment]
Could you trying again after pulling the latest version? I found somewhere I wasn't closing the temporary databases, which might be what is causing the issue.

**Comment by katkasian** [comment]
Thank you, Sam, it's working!
